services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${FORWARD_DB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: